"""FlowScope PDF Exporter.

Renders curated Markdown guides or annotated session blocks into structured,
professional PDF documents using ReportLab.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

try:
    import markdown
except ImportError:
    markdown = None  # type: ignore

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and print total page count and header/footer."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#64748b"))  # Slate grey

        # Top Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(36, 756, "FlowScope Technical Guide")
            self.setStrokeColor(colors.HexColor("#cbd5e1"))
            self.setLineWidth(0.5)
            self.line(36, 750, 576, 750)

        # Bottom Footer (all pages)
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(36, 45, 576, 45)

        footer_text = "Generated by FlowScope"
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawString(36, 30, footer_text)
        self.drawRightString(576, 30, page_str)

        self.restoreState()


def _build_styles() -> dict[str, ParagraphStyle]:
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0f172a"),  # Dark Navy
        spaceAfter=12,
    )

    h1_style = ParagraphStyle(
        "DocH1",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=16,
        spaceAfter=8,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        "DocH2",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#2563eb"),  # Royal Blue
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True,
    )

    h3_style = ParagraphStyle(
        "DocH3",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#334155"),
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        "DocBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#334155"),
        spaceAfter=8,
    )

    bullet_style = ParagraphStyle(
        "DocBullet",
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4,
    )

    code_style = ParagraphStyle(
        "CodeText",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#0f172a"),
    )

    callout_style = ParagraphStyle(
        "CalloutText",
        parent=body_style,
        fontName="Helvetica-Oblique",
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#475569"),
    )

    return {
        "Title": title_style,
        "H1": h1_style,
        "H2": h2_style,
        "H3": h3_style,
        "Body": body_style,
        "Bullet": bullet_style,
        "Code": code_style,
        "Callout": callout_style,
    }


def parse_markdown_to_flowables(md_content: str, styles: dict[str, ParagraphStyle]) -> list:
    """Parses markdown string into ReportLab flowables."""
    flowables = []
    lines = md_content.splitlines()

    i = 0
    in_code_block = False
    code_lines = []
    code_lang = ""

    while i < len(lines):
        line = lines[i]

        # Code block fence toggle
        if line.strip().startswith("```"):
            if not in_code_block:
                in_code_block = True
                code_lang = line.strip().lstrip("`").strip()
                code_lines = []
            else:
                in_code_block = False
                code_text = "\n".join(code_lines)
                if code_text:
                    # Render code box as styled table
                    p = Preformatted(code_text, styles["Code"])
                    tbl = Table([[p]], colWidths=[540])
                    tbl.setStyle(
                        TableStyle(
                            [
                                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                                ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#cbd5e1")),
                                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                                ("TOPPADDING", (0, 0), (-1, -1), 8),
                                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                            ]
                        )
                    )
                    flowables.append(Spacer(1, 4))
                    flowables.append(tbl)
                    flowables.append(Spacer(1, 8))
            i += 1
            continue

        if in_code_block:
            code_lines.append(line)
            i += 1
            continue

        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # Horizontal Rule
        if stripped in ("---", "***", "___"):
            flowables.append(Spacer(1, 4))
            flowables.append(
                HRFlowable(
                    width="100%",
                    thickness=0.75,
                    color=colors.HexColor("#e2e8f0"),
                    spaceBefore=6,
                    spaceAfter=10,
                )
            )
            i += 1
            continue

        # Headers
        if stripped.startswith("# "):
            title_text = _clean_inline_markdown(stripped[2:])
            flowables.append(Paragraph(title_text, styles["Title"]))
            flowables.append(
                HRFlowable(
                    width="100%",
                    thickness=1.5,
                    color=colors.HexColor("#2563eb"),
                    spaceBefore=2,
                    spaceAfter=12,
                )
            )
            i += 1
            continue
        elif stripped.startswith("## "):
            h2_text = _clean_inline_markdown(stripped[3:])
            # Check for category badge like [SETUP], [CONFIG]
            h2_html = _format_header_badges(h2_text)
            flowables.append(Paragraph(h2_html, styles["H2"]))
            i += 1
            continue
        elif stripped.startswith("### "):
            h3_text = _clean_inline_markdown(stripped[4:])
            flowables.append(Paragraph(h3_text, styles["H3"]))
            i += 1
            continue

        # Bullet List Items
        if stripped.startswith("- ") or stripped.startswith("* "):
            item_text = _clean_inline_markdown(stripped[2:])
            flowables.append(Paragraph(f"• {item_text}", styles["Bullet"]))
            i += 1
            continue

        # Expected Output / Callout lines (e.g. *Expected Output:* ...)
        if stripped.startswith("*Expected Output:*") or stripped.startswith("> "):
            callout_text = _clean_inline_markdown(stripped.lstrip("> ").strip())
            p = Paragraph(callout_text, styles["Callout"])
            tbl = Table([[p]], colWidths=[540])
            tbl.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f1f5f9")),
                        ("LINELEFT", (0, 0), (0, 0), 3, colors.HexColor("#3b82f6")),
                        ("LEFTPADDING", (0, 0), (-1, -1), 8),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                        ("TOPPADDING", (0, 0), (-1, -1), 6),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ]
                )
            )
            flowables.append(Spacer(1, 4))
            flowables.append(tbl)
            flowables.append(Spacer(1, 6))
            i += 1
            continue

        # Standard Paragraph
        para_text = _clean_inline_markdown(stripped)
        flowables.append(Paragraph(para_text, styles["Body"]))
        i += 1

    return flowables


def _clean_inline_markdown(text: str) -> str:
    """Converts basic markdown inline styles (bold, italic, code) to ReportLab XML tags."""
    # Escape XML special chars
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    # Bold: **text** -> <b>text</b>
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    # Italic: *text* -> <i>text</i>
    text = re.sub(r"\*(.*?)\*", r"<i>\1</i>", text)
    # Inline code: `code` -> <font name="Courier" color="#1e293b">code</font>
    text = re.sub(
        r"`(.*?)`",
        r'<font name="Courier" color="#1e293b" size="9"><b>\1</b></font>',
        text,
    )

    return text


def _format_header_badges(text: str) -> str:
    """Formats category tags like [SETUP] or [CONFIG] into styled colored badges."""
    badge_colors = {
        "SETUP": "#10b981",       # Emerald
        "DEPENDENCY": "#0284c7",  # Sky Blue
        "CONFIG": "#8b5cf6",      # Purple
        "BUILD": "#f59e0b",       # Amber
        "EXECUTION": "#2563eb",   # Blue
        "VERIFICATION": "#059669",# Green
        "CLEANUP": "#64748b",     # Slate
    }

    def replace_badge(match):
        tag = match.group(1).upper()
        color = badge_colors.get(tag, "#3b82f6")
        return f' <font color="{color}"><b>[{tag}]</b></font>'

    return re.sub(r"\[([A-Za-z0-9_-]+)\]", replace_badge, text)


def render_markdown_to_pdf(
    md_content: str, output_path: Path, doc_title: str | None = None
) -> Path:
    """Converts a Markdown string to a rendered PDF document."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=54,
        bottomMargin=54,
    )

    styles = _build_styles()
    flowables = parse_markdown_to_flowables(md_content, styles)

    doc.build(flowables, canvasmaker=NumberedCanvas)
    return output_path


def render_pdf_file(input_path: Path, output_path: Path) -> Path:
    """Reads a Markdown or JSON blocks file and converts it into a PDF document."""
    input_path = Path(input_path)
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    content = input_path.read_text(encoding="utf-8")

    # If input is blocks JSON, convert via flowscope_markdown if available
    if input_path.suffix == ".json":
        try:
            import flowscope_markdown

            content = flowscope_markdown.render_markdown(input_path)
        except Exception:
            pass

    return render_markdown_to_pdf(content, output_path)


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(f"Usage: {sys.argv[0]} <input.md|blocks.json> [--out output.pdf]")

    input_path = Path(sys.argv[1])
    out_path = input_path.with_suffix(".pdf")

    if "--out" in sys.argv or "-o" in sys.argv:
        idx = sys.argv.index("--out") if "--out" in sys.argv else sys.argv.index("-o")
        out_path = Path(sys.argv[idx + 1])

    res = render_pdf_file(input_path, out_path)
    print(f"PDF guide successfully generated at: {res}")


if __name__ == "__main__":
    main()